name: flutter_chatbot
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.1+12

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^1.1.0
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0
  google_sign_in: ^4.5.1
  apple_sign_in: ^0.1.0
  provider: ^4.1.3
  flutter_auth_buttons: ^0.8.0
  cloud_firestore: ^0.14.0
  font_awesome_flutter: ^8.8.1
  bubble: ^1.1.9+1
  google_fonts: ^1.1.0
  flutter_svg: ^0.19.3
  uuid: ^2.2.2
  http: ^0.12.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: '^0.8.0'

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/therabot.png'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Cb
      fonts:
        - asset: assets/fonts/Cb.ttf
        - asset: assets/fonts/Restart.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/dartmouth_logo.png
    - assets/credentials/simplechatbot-pkhufy-24d22513a231.json
    - assets/bots/bot_transparent.gif
    - assets/bots/bot_transparent1.gif
    - assets/images/bot_logo.svg
    - assets/images/therabot.svg
    - assets/images/onboardDesign.png
    - assets/images/onboardFeedback.png
    - assets/images/onboardModes.png
    - assets/images/onboardTalk.png
    - assets/images/OR.svg
    - assets/images/google.svg
    - assets/images/apple.svg

    # animations
    - assets/animations/CB1/terror2/
    - assets/animations/CB1/happy_nod6/
    - assets/animations/CB1/happy_nod1/
    - assets/animations/CB1/sad_think2/
    - assets/animations/CB1/sad_anticipation2/
    - assets/animations/CB1/happy_think1/
    - assets/animations/CB1/anxiety2/
    - assets/animations/CB1/sad_think4/
    - assets/animations/CB1/sad_think3/
    - assets/animations/CB1/disgust1/
    - assets/animations/CB1/sad_surprise1/
    - assets/animations/CB1/happy_surprise1/
    - assets/animations/CB1/happy_idle2/
    - assets/animations/CB1/anger1/
    - assets/animations/CB1/happy_idle5/
    - assets/animations/CB1/happy_anticipation2/
    - assets/animations/CB1/sad_nod1/
    - assets/animations/CB1/sad_nod6/
    - assets/animations/CB1/happy_idle4/
    - assets/animations/CB1/happy_idle3/
    - assets/animations/CB1/happy_idle10/
    - assets/animations/CB1/sad_idle12/
    - assets/animations/CB1/sad_trust2/
    - assets/animations/CB1/happy_trust1/
    - assets/animations/CB1/happy_idle11/
    - assets/animations/CB1/fear2/
    - assets/animations/CB1/sad_idle2/
    - assets/animations/CB1/depression1/
    - assets/animations/CB1/sad_idle5/
    - assets/animations/CB1/sad1/
    - assets/animations/CB1/joy3/
    - assets/animations/CB1/sad_idle4/
    - assets/animations/CB1/sad_idle3/
    - assets/animations/CB1/joy2/
    - assets/animations/CB1/sad_think1/
    - assets/animations/CB1/terror1/
    - assets/animations/CB1/happy_think4/
    - assets/animations/CB1/happy_think3/
    - assets/animations/CB1/happy_nod2/
    - assets/animations/CB1/happy_nod5/
    - assets/animations/CB1/anxiety1/
    - assets/animations/CB1/sad_anticipation1/
    - assets/animations/CB1/happy_nod4/
    - assets/animations/CB1/happy_nod3/
    - assets/animations/CB1/happy_think2/
    - assets/animations/CB1/anger2/
    - assets/animations/CB1/happy_idle6/
    - assets/animations/CB1/happy_idle1/
    - assets/animations/CB1/sad_nod3/
    - assets/animations/CB1/happy_idle8/
    - assets/animations/CB1/sad_nod4/
    - assets/animations/CB1/happy_anticipation1/
    - assets/animations/CB1/disgust2/
    - assets/animations/CB1/happy_surprise2/
    - assets/animations/CB1/sad_surprise2/
    - assets/animations/CB1/sad_nod5/
    - assets/animations/CB1/happy_idle9/
    - assets/animations/CB1/sad_nod2/
    - assets/animations/CB1/happy_idle7/
    - assets/animations/CB1/sad_idle11/
    - assets/animations/CB1/sad_trust1/
    - assets/animations/CB1/sad_idle10/
    - assets/animations/CB1/fear1/
    - assets/animations/CB1/happy_trust2/
    - assets/animations/CB1/happy_idle12/
    - assets/animations/CB1/sad_idle8/
    - assets/animations/CB1/depression2/
    - assets/animations/CB1/sad2/
    - assets/animations/CB1/sad_idle6/
    - assets/animations/CB1/sad_idle1/
    - assets/animations/CB1/joy1/
    - assets/animations/CB1/sad_idle7/
    - assets/animations/CB1/sad_idle9/

    # old animations
    - assets/animations/idle/happy_idle1/
    - assets/animations/idle/happy_idle2/
    - assets/animations/happy/CB1.Happy.Idle1/
    - assets/animations/happy/CB1.Happy.Idle2/
    - assets/animations/happy/CB1.Happy.Idle3/
    - assets/animations/happy/CB1.Happy.Idle4/
    - assets/animations/happy/CB1.Happy.Idle5/
    - assets/animations/sad/CB1.Sad.Idle1/
    - assets/animations/sad/CB1.Sad.Idle2/
    - assets/animations/sad/CB1.Sad.Idle3/
    - assets/animations/sad/CB1.Sad.Idle4/
    - assets/animations/sad/CB1.Sad.Idle5/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
