/// Flutter icons ChatbotIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ChatbotIcons
///      fonts:
///       - asset: fonts/ChatbotIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ChatbotIcons {
  ChatbotIcons._();

  static const _kFontFam = 'ChatbotIcons';
  static const _kFontPkg = null;

  static const IconData feedbackcheck = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feedbackex = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feedbackcomment = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feedbackcheckpressed = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feedbackexpressed = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feedbackcommentpressed = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feedbackmultichoice = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feedbackmultichoiceselected = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
